CONTIKI_PROJECT = timer-test
all: $(CONTIKI_PROJECT)

CONTIKI = ../../contiki
OPENCM3_BASE=../../libopencm3
#OPENCM3_BASE=libopencm3
TARGETDIRS += ../../platform

include $(CONTIKI)/Makefile.include

